"""empty message

Revision ID: 9e4d7b0afc1d
Revises: 
Create Date: 2026-09-30 03:13:58.927518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e4d7b0afc1d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('board', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('player_x_id', sa.UUID(), nullable=False),
    sa.Column('player_o_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('WAITING_FOR_PLAYER', 'PLAYER_TURN', 'DRAW', 'WIN', name='game_status'), nullable=False),
    sa.Column('status_player_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_table('users')
    op.drop_table('games')
    # ### end Alembic commands ###
